#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from datetime import datetime
import sys
import os
import argparse
import numpy as np
import pandas as pd

from katana.framework import Katana

def run():
    '''
    katana is a command line program designed to take a config file. This
    will be fed to the run_katana function within framework.
    '''

    # Parse arguments
    p = argparse.ArgumentParser(description='Run Katana wind system.')

    p.add_argument('cfg', metavar='c', type=str,
                   help='Path to config file')


    args = p.parse_args()

    cfg = args.cfg

    if not os.path.isfile(cfg):
        raise IOError('Not a correct path to config file')
        
    # run the katana framework
    with Katana(cfg) as k:
        k.run_katana()

if __name__ == '__main__':

    run()
